# 2004Scape (LostCityRS rev 274) Archipelago world.
#
# See 2004Scape-AP-Logic/docs/archipelago-integration.md for the full design.
# Everything data-driven comes from data/rs2004_data.json, generated by
# tools/ap/ExportApWorldData.ts from the same PlacementEngine catalogs the local
# solo placement mode uses - this file only interprets that data:
#
# - Locations: the check catalog (quests, DS stages, barcrawl bars, first-xp,
#   first-kill, level milestones, activities, music tracks).
# - Items: Progressive gear/tool tiers, Progressive <Skill> Cap (+20 levels
#   each; the game engine's cap formula is 20 + 10*grant_count and the client
#   grants +2 per copy), Quest Unlock gates, and Mystery Reward filler.
# - Rules: a direct port of PlacementEngine.reachableFromState +
#   Engine.completableQuests (travel-agnostic; the game server independently
#   guarantees entrance-shuffle reachability - see the design doc).
#
# Quest completions are modeled as events ("Completed: <id>") so rules can
# require them; QP is summed from completed-quest events inside rule lambdas.

import json
import pkgutil

from BaseClasses import Item, ItemClassification, Location, LocationProgressType, Region, Tutorial
from Options import OptionError
from worlds.AutoWorld import WebWorld, World
from worlds.generic.Rules import set_rule

from .options import Goal, RS2004Options

DATA = json.loads(pkgutil.get_data(__name__, "data/rs2004_data.json").decode("utf-8"))

GAME_NAME = DATA["game"]

# quests.json records, keyed by quest id
QUESTS = {q["id"]: q for q in DATA["quests"]}
GATED_QUEST_IDS = set(DATA["questGates"])

# location catalog keyed by engine check id
LOCATIONS = DATA["locations"]
ITEMS = DATA["items"]

CAP_ITEM_BY_SKILL = {}
for _name, _def in ITEMS.items():
    if _name.startswith("Progressive ") and _name.endswith(" Cap"):
        CAP_ITEM_BY_SKILL[_name[len("Progressive "):-len(" Cap")].lower()] = _name

QUEST_UNLOCK_ITEM_BY_ID = {}
for _name, _def in ITEMS.items():
    if _def.get("grant", "").startswith("quest_"):
        QUEST_UNLOCK_ITEM_BY_ID[_def["grant"][len("quest_"):]] = _name

FILLER_NAME = "Mystery Reward"
PROGRESSIVE_QUEST_NAME = "Progressive Quest Unlock"

GEAR_ITEM_NAMES = {"Progressive Melee", "Progressive Armour", "Progressive Ranged", "Progressive Magic"}
TOOL_ITEM_NAMES = {"Progressive Pickaxe", "Progressive Axe"}

# difficulty-ordered gated quests; copy N of the progressive item unlocks entry N-1
QUEST_ORDER = DATA["questUnlockOrder"]
QUEST_ORDER_INDEX = {qid: i for i, qid in enumerate(QUEST_ORDER)}

# option value / OptionSet key -> slot_data goal key (the goalChecks vocabulary)
GOAL_KEY_BY_NAME = {
    "dragon_slayer": "dragon",
    "barcrawl": "barcrawl",
    "kbd": "kbd",
    "heroes": "heroes",
    "legends": "legends",
}


def cap_copies_needed(level: int) -> int:
    """Copies of a skill's cap item needed to train to `level` (cap = 20 + 20/copy)."""
    if level <= 20:
        return 0
    return -(-(level - 20) // 20)  # ceil div


class RS2004Item(Item):
    game = GAME_NAME


class RS2004Location(Location):
    game = GAME_NAME


class RS2004Web(WebWorld):
    theme = "grass"
    bug_report_page = "https://github.com/marcdubs/2004Scape-AP-Logic/issues"
    tutorials = [Tutorial(
        "Multiworld Setup Guide",
        "A guide to setting up the 2004Scape game server and connecting it to an Archipelago multiworld.",
        "English",
        "setup_en.md",
        "setup/en",
        ["Marcus Dubreuil"],
    )]


class RS2004World(World):
    """2004scape - the open-source Lost City game server (rev 274) - randomized:
    progressive gear and tool tiers, skill level caps, quest gates, and a world
    full of shuffled entrances, drops, shops and recipes on the game-server side."""

    game = GAME_NAME
    options_dataclass = RS2004Options
    options: RS2004Options
    web = RS2004Web()

    item_name_to_id = {name: d["id"] for name, d in ITEMS.items()}
    location_name_to_id = {loc["name"]: loc["id"] for loc in LOCATIONS.values()}

    item_name_groups = {
        "Skill Caps": set(CAP_ITEM_BY_SKILL.values()),
        "Quest Unlocks": set(QUEST_UNLOCK_ITEM_BY_ID.values()) | {PROGRESSIVE_QUEST_NAME},
        "Gear and Tools": {
            name for name, d in ITEMS.items()
            if name not in set(CAP_ITEM_BY_SKILL.values())
            and name not in set(QUEST_UNLOCK_ITEM_BY_ID.values())
            and name != PROGRESSIVE_QUEST_NAME
            and not d.get("filler")
        },
    }

    _KIND_GROUP = {
        "quest": "Quests",
        "ds": "Dragon Slayer Stages",
        "barcrawl": "Barcrawl Bars",
        "level": "Level Milestones",
        "activity": "Activities",
        "first_xp": "First XP",
        "first_kill": "First Kills",
        "music": "Music Tracks",
    }
    location_name_groups = {}
    for _loc in LOCATIONS.values():
        location_name_groups.setdefault(_KIND_GROUP[_loc["kind"]], set()).add(_loc["name"])
    del _loc

    # ------------------------------------------------------------------
    # rules (ports of PlacementEngine.reachableFromState semantics)
    # ------------------------------------------------------------------

    def _has_cap(self, state, skill: str, level: int) -> bool:
        if not self.options.skill_caps:
            return True  # caps disabled: no skill is ever capped
        if skill == "hitpoints":
            return True  # hitpoints is never capped
        need = cap_copies_needed(level)
        if need == 0:
            return True
        item = CAP_ITEM_BY_SKILL.get(skill)
        return item is not None and state.has(item, self.player, need)

    def _qp(self, state) -> int:
        total = 0
        for qid, quest in QUESTS.items():
            if state.has(f"Completed: {qid}", self.player):
                total += quest["qp"]
        return total

    def _quest_rule(self, state, qid: str) -> bool:
        quest = QUESTS[qid]

        if qid in GATED_QUEST_IDS and self.options.quest_unlocks:
            if self.options.progressive_quests:
                need = QUEST_ORDER_INDEX[qid] + 1
                if not state.has(PROGRESSIVE_QUEST_NAME, self.player, need):
                    return False
            else:
                unlock = QUEST_UNLOCK_ITEM_BY_ID.get(qid)
                if unlock is not None and not state.has(unlock, self.player):
                    return False

        for skill, level in (quest.get("skills") or {}).items():
            if not self._has_cap(state, skill, level):
                return False

        for prereq in quest.get("quests") or []:
            if not state.has(f"Completed: {prereq}", self.player):
                return False

        for group in quest.get("questsAny") or []:
            if not any(state.has(f"Completed: {alt}", self.player) for alt in group):
                return False

        required_qp = quest.get("requiredQp")
        if required_qp and self._qp(state) < required_qp:
            return False

        return True

    def _location_rule(self, state, check_id: str) -> bool:
        loc = LOCATIONS[check_id]
        kind = loc["kind"]
        if kind == "quest":
            return self._quest_rule(state, loc["questId"])
        if kind == "ds":
            # DS stage checks collapse to the quest's startability (QP >= 32),
            # same as reachableFromState.
            required_qp = QUESTS["dragon"].get("requiredQp") or 0
            return self._qp(state) >= required_qp
        if kind in ("level", "activity"):
            skill = loc.get("skill")
            level = loc.get("level")
            if skill is None or level is None:
                return True
            return self._has_cap(state, skill, level)
        # barcrawl / first_xp / first_kill / music: sphere 0
        return True

    # ------------------------------------------------------------------
    # generation hooks
    # ------------------------------------------------------------------

    def create_regions(self) -> None:
        menu = Region("Menu", self.player, self.multiworld)
        gielinor = Region("Gielinor", self.player, self.multiworld)
        self.multiworld.regions += [menu, gielinor]
        menu.connect(gielinor)

        include_music = bool(self.options.music_checks)

        for check_id, loc in LOCATIONS.items():
            if loc["kind"] == "music" and not include_music:
                continue
            location = RS2004Location(self.player, loc["name"], loc["id"], gielinor)
            if loc.get("fillerOnly"):
                # luck-gated (clue drops) or deliberately-not-progression (music)
                location.progress_type = LocationProgressType.EXCLUDED
            set_rule(location, lambda state, cid=check_id: self._location_rule(state, cid))
            gielinor.locations.append(location)

        # quest-completion events, so rules can require "Completed: <id>"
        for qid in QUESTS:
            event = RS2004Location(self.player, f"Event: Completed {qid}", None, gielinor)
            event.place_locked_item(RS2004Item(f"Completed: {qid}", ItemClassification.progression, None, self.player))
            set_rule(event, lambda state, q=qid: self._quest_rule(state, q))
            gielinor.locations.append(event)

        # victory event: EVERY configured goal (goal + extra_goals) must hold
        victory = RS2004Location(self.player, "Event: Victory", None, gielinor)
        victory.place_locked_item(RS2004Item("Victory", ItemClassification.progression, None, self.player))
        goal_keys = self._goal_keys()
        set_rule(victory, lambda state: all(self._goal_rule(state, key) for key in goal_keys))
        gielinor.locations.append(victory)

        self.multiworld.completion_condition[self.player] = lambda state: state.has("Victory", self.player)

    def _goal_keys(self) -> list:
        primary = {
            Goal.option_dragon_slayer: "dragon",
            Goal.option_barcrawl: "barcrawl",
            Goal.option_kbd: "kbd",
            Goal.option_heroes: "heroes",
            Goal.option_legends: "legends",
        }[self.options.goal.value]
        keys = [primary]
        for name in sorted(self.options.extra_goals.value):
            key = GOAL_KEY_BY_NAME[name]
            if key not in keys:
                keys.append(key)
        return keys

    def _goal_rule(self, state, key: str) -> bool:
        if key == "dragon":
            return state.has("Completed: dragon", self.player)
        if key == "barcrawl":
            return True  # the bars are a sphere-0 travel checklist
        if key == "kbd":
            return all(self._has_cap(state, s, 50) for s in ("attack", "strength", "defence"))
        if key == "heroes":
            return state.has("Completed: hero", self.player)
        # legends
        return state.has("Completed: legends", self.player)

    def create_item(self, name: str) -> RS2004Item:
        item_def = ITEMS[name]
        classification = ItemClassification.filler if item_def.get("filler") else ItemClassification.progression
        return RS2004Item(name, classification, item_def["id"], self.player)

    def create_items(self) -> None:
        # progressive mode swaps the per-quest unlocks for an equal number of
        # copies of the progressive item; classic mode skips the progressive item
        per_quest_unlocks = set(QUEST_UNLOCK_ITEM_BY_ID.values())
        progressive = bool(self.options.progressive_quests)
        skipped = set()
        if not self.options.gear_progression:
            skipped |= GEAR_ITEM_NAMES
        if not self.options.tool_progression:
            skipped |= TOOL_ITEM_NAMES
        if not self.options.skill_caps:
            skipped |= set(CAP_ITEM_BY_SKILL.values())
        if not self.options.quest_unlocks:
            skipped |= per_quest_unlocks | {PROGRESSIVE_QUEST_NAME}
        elif progressive:
            skipped |= per_quest_unlocks
        else:
            skipped.add(PROGRESSIVE_QUEST_NAME)
        pool = []
        for name, item_def in ITEMS.items():
            if name in skipped:
                continue
            for _ in range(item_def.get("copies", 0)):
                pool.append(self.create_item(name))

        real_locations = len([loc for loc in self.multiworld.get_locations(self.player) if loc.address is not None])
        while len(pool) < real_locations:
            pool.append(self.create_item(FILLER_NAME))
        if len(pool) > real_locations:
            raise OptionError(f"2004Scape: item pool ({len(pool)}) exceeds locations ({real_locations}) - enable more checks (music_checks)")

        self.multiworld.itempool += pool

    def get_filler_item_name(self) -> str:
        return FILLER_NAME

    def fill_slot_data(self) -> dict:
        goal_keys = self._goal_keys()
        quest_unlocks = bool(self.options.quest_unlocks.value)
        return {
            "goal": goal_keys[0],  # pre-multi-goal servers read this
            "goals": goal_keys,
            "gearProgression": bool(self.options.gear_progression.value),
            "toolProgression": bool(self.options.tool_progression.value),
            "skillCaps": bool(self.options.skill_caps.value),
            "progressiveQuests": quest_unlocks and bool(self.options.progressive_quests.value),
            "relics": sorted(self.options.relics.value),
            "musicChecks": bool(self.options.music_checks.value),
            "infiniteRun": bool(self.options.infinite_run.value),
            # seed knobs: the game server adopts these on connect and applies
            # them the next time it rolls a seed (scripts/new-run)
            "seedOptions": {
                "entrances": self.options.entrance_randomization.current_key,
                "npcDrip": bool(self.options.npc_drip.value),
                "shops": bool(self.options.shop_randomization.value),
                "teleports": bool(self.options.teleport_randomization.value),
                "drops": self.options.drop_randomization.current_key,
                "gathering": self.options.gathering_randomization.current_key,
                "processing": self.options.processing_randomization.current_key,
                "spawn": self.options.spawn_randomization.current_key,
            },
            # no quest unlock items -> no gates: the server leaves every quest open
            "questGates": sorted(GATED_QUEST_IDS) if quest_unlocks else []
        }
