import fs from 'fs';
import path from 'path';

import { printInfo, printWarning } from '#/util/Logger.js';

// Backing store for the ap_drop_group script command (Archipelago drop randomizer,
// --mode mimic). Maps a drop-table slot index (baked into each monster death handler's
// preamble by tools/drops/RandomizeDrops.ts --mode mimic) to the index of the loot
// table it should run instead of its own - "chicken mimics green dragon".
//
// Same architecture as ApEntranceOverrides.ts: the table is generated by the tool and
// lives outside the compiled script pack on purpose, so reseeding only requires
// swapping this file and restarting the server - no content rebuild (the preambles,
// dispatch label, and extracted loot labels are seed-independent; only this mapping
// changes per seed). A missing or empty file means every lookup misses and the
// preambles fall through to vanilla loot.

const OVERRIDES_PATH = 'data/config/ap-drops.json';

let overrides: Map<number, number> | null = null;

function load(): Map<number, number> {
    const table = new Map<number, number>();

    if (!fs.existsSync(OVERRIDES_PATH)) {
        printInfo(`AP drop overrides: no ${path.basename(OVERRIDES_PATH)}, drop tables are vanilla`);
        return table;
    }

    try {
        const parsed = JSON.parse(fs.readFileSync(OVERRIDES_PATH, 'utf8')) as { map?: Record<string, number> };
        for (const [slot, unit] of Object.entries(parsed.map ?? {})) {
            if (!/^\d+$/.test(slot) || !Number.isInteger(unit) || unit < 0) {
                printWarning(`AP drop overrides: skipping malformed entry ${slot} -> ${unit}`);
                continue;
            }
            table.set(parseInt(slot, 10), unit);
        }
        printInfo(`AP drop overrides: loaded ${table.size} table redirect(s)`);
    } catch (err) {
        printWarning(`AP drop overrides: failed to parse ${OVERRIDES_PATH}, drop tables are vanilla (${err instanceof Error ? err.message : err})`);
    }

    return table;
}

// returns the replacement loot-table unit index for a slot, or -1 (script null) on miss.
export function getDropGroupOverride(slot: number): number {
    if (overrides === null) {
        overrides = load();
    }
    return overrides.get(slot) ?? -1;
}
