import fs from 'fs';
import path from 'path';

import { CoordGrid } from '#/engine/CoordGrid.js';
import { printInfo, printWarning } from '#/util/Logger.js';

// Backing store for the ap_entrance_override script command (Archipelago entrance
// randomizer). Maps a ladder/stair trigger coordinate to a replacement destination.
//
// The table is generated by tools/map/RandomizeEntrances.ts and lives outside the
// compiled script pack on purpose: reseeding only requires swapping this file and
// restarting the server - no content rebuild. A missing or empty file means every
// lookup misses and the patched handlers fall through to vanilla behavior.

const OVERRIDES_PATH = 'data/config/ap-entrances.json';

// keys are "level_mapX_mapZ_localX_localZ:op" (op distinguishes climb-up from
// climb-down on the same tile, e.g. spiral staircase middle landings); values are
// plain coord literals.
const KEY_RE = /^\d+_\d+_\d+_\d+_\d+:\d+$/;
const COORD_RE = /^\d+_\d+_\d+_\d+_\d+$/;

function packFromString(raw: string): number {
    const [level, mapX, mapZ, localX, localZ] = raw.split('_').map(Number);
    return CoordGrid.packCoord(level, (mapX << 6) + localX, (mapZ << 6) + localZ);
}

let overrides: Map<string, number> | null = null;

function load(): Map<string, number> {
    const table = new Map<string, number>();

    if (!fs.existsSync(OVERRIDES_PATH)) {
        printInfo(`AP entrance overrides: no ${path.basename(OVERRIDES_PATH)}, entrances are vanilla`);
        return table;
    }

    try {
        const parsed = JSON.parse(fs.readFileSync(OVERRIDES_PATH, 'utf8')) as { overrides?: Record<string, string> };
        for (const [from, to] of Object.entries(parsed.overrides ?? {})) {
            if (!KEY_RE.test(from) || !COORD_RE.test(to)) {
                printWarning(`AP entrance overrides: skipping malformed entry ${from} -> ${to}`);
                continue;
            }
            const [coordRaw, op] = from.split(':');
            table.set(`${packFromString(coordRaw)}:${op}`, packFromString(to));
        }
        printInfo(`AP entrance overrides: loaded ${table.size} redirect(s)`);
    } catch (err) {
        printWarning(`AP entrance overrides: failed to parse ${OVERRIDES_PATH}, entrances are vanilla (${err instanceof Error ? err.message : err})`);
    }

    return table;
}

// returns the override destination as a packed coord, or -1 (script null) on miss.
export function getEntranceOverride(packedCoord: number, op: number): number {
    if (overrides === null) {
        overrides = load();
    }
    return overrides.get(`${packedCoord}:${op}`) ?? -1;
}
