import fs from 'fs';
import path from 'path';

import { printInfo, printWarning } from '#/util/Logger.js';

// Backing store for the ap_gather_swap script command (Archipelago gathering-skill
// randomizer). Maps a gathering product's obj id to the obj id actually handed to the
// player - "cut a tree, get a fish". Generated by tools/gather/RandomizeGathering.ts.
//
// Same architecture as ApEntranceOverrides.ts/ApDropOverrides.ts: the table lives
// outside the compiled script pack on purpose, so reseeding only requires swapping
// this file and restarting the server - no content rebuild (the ap_gather_swap()
// wraps at each skill's inv_add delivery point are seed-independent; only this
// mapping changes per seed).
//
// Unlike the other two loaders, a miss returns the INPUT id rather than -1: the
// natural miss semantics for an item transform is "unchanged", and it lets every
// content chokepoint be a pure one-token wrap - inv_add(inv, ap_gather_swap($x), 1) -
// with no null branch. A missing or empty file therefore means every gathering
// product is vanilla.

const OVERRIDES_PATH = 'data/config/ap-gather.json';

let overrides: Map<number, number> | null = null;

function load(): Map<number, number> {
    const table = new Map<number, number>();

    if (!fs.existsSync(OVERRIDES_PATH)) {
        printInfo(`AP gather overrides: no ${path.basename(OVERRIDES_PATH)}, gathering products are vanilla`);
        return table;
    }

    try {
        const parsed = JSON.parse(fs.readFileSync(OVERRIDES_PATH, 'utf8')) as { map?: Record<string, number> };
        for (const [product, replacement] of Object.entries(parsed.map ?? {})) {
            if (!/^\d+$/.test(product) || !Number.isInteger(replacement) || replacement < 0) {
                printWarning(`AP gather overrides: skipping malformed entry ${product} -> ${replacement}`);
                continue;
            }
            table.set(parseInt(product, 10), replacement);
        }
        printInfo(`AP gather overrides: loaded ${table.size} product swap(s)`);
    } catch (err) {
        printWarning(`AP gather overrides: failed to parse ${OVERRIDES_PATH}, gathering products are vanilla (${err instanceof Error ? err.message : err})`);
    }

    return table;
}

// returns the replacement obj id for a gathering product, or the product itself
// (vanilla passthrough) on miss.
export function getGatherSwap(product: number): number {
    if (overrides === null) {
        overrides = load();
    }
    return overrides.get(product) ?? product;
}
