// Archipelago random spawn/home point (2004Scape-AP-Logic docs/goals-and-checks.md
// Feature 3, expanded: city mode picks one of the 7 standard-spellbook teleport
// landmarks, chunk mode picks a random mainland mapsquare). Backing store for the
// ap_home_coord script command, the death-respawn override, the ::home cheat, and
// (via getHomeCoord) the skip-tutorial new-player spawn.
//
// Loading conventions mirror ApEntranceOverrides.ts exactly: lazy-load once on first
// use, missing/invalid file = vanilla fallback, no mid-session reload (this is
// per-seed data - reseed = rewrite JSON + restart, same as every other Ap*Overrides
// module). Table is generated by tools/spawn/RandomizeSpawn.ts.

import fs from 'fs';
import path from 'path';

import { CoordGrid } from '#/engine/CoordGrid.js';
import { printInfo, printWarning } from '#/util/Logger.js';

const OVERRIDES_PATH = 'data/config/ap-spawn.json';

// "level_mapX_mapZ_localX_localZ" - same human-readable coord literal convention as
// ap-entrances.json / the vanilla dbrow tele_coord values.
const COORD_RE = /^\d+_\d+_\d+_\d+_\d+$/;
const MODE_RE = /^(city|chunk)$/;

// Vanilla Lumbridge respawn: 0_50_50_21_18 (death.rs2's hardcoded coord).
const VANILLA_HOME = CoordGrid.packCoord(0, 50 * 64 + 21, 50 * 64 + 18);
const VANILLA_LABEL = 'Lumbridge (vanilla)';

function packFromString(raw: string): number {
    const [level, mapX, mapZ, localX, localZ] = raw.split('_').map(Number);
    return CoordGrid.packCoord(level, (mapX << 6) + localX, (mapZ << 6) + localZ);
}

type SpawnFile = { home?: string; mode?: string; seed?: number; label?: string };
type SpawnState = { coord: number; mode: 'city' | 'chunk' | 'vanilla'; seed: number | null; label: string };

let state: SpawnState | null = null;

function fallback(): SpawnState {
    return { coord: VANILLA_HOME, mode: 'vanilla', seed: null, label: VANILLA_LABEL };
}

function load(): SpawnState {
    if (!fs.existsSync(OVERRIDES_PATH)) {
        printInfo(`AP spawn override: no ${path.basename(OVERRIDES_PATH)}, home is vanilla Lumbridge`);
        return fallback();
    }

    try {
        const parsed = JSON.parse(fs.readFileSync(OVERRIDES_PATH, 'utf8')) as SpawnFile;

        if (!parsed.home || !COORD_RE.test(parsed.home)) {
            printWarning(`AP spawn override: missing/malformed "home" in ${OVERRIDES_PATH}, home is vanilla Lumbridge`);
            return fallback();
        }

        const mode = parsed.mode && MODE_RE.test(parsed.mode) ? (parsed.mode as 'city' | 'chunk') : 'city';
        if (parsed.mode && !MODE_RE.test(parsed.mode)) {
            printWarning(`AP spawn override: unrecognized mode "${parsed.mode}" in ${OVERRIDES_PATH}, defaulting to "city"`);
        }

        const coord = packFromString(parsed.home);
        const label = typeof parsed.label === 'string' && parsed.label.length > 0 ? parsed.label : (() => {
            const { x, z } = CoordGrid.unpackCoord(coord);
            return `mapsquare ${x >> 6},${z >> 6}`;
        })();
        const seed = typeof parsed.seed === 'number' ? parsed.seed : null;

        printInfo(`AP spawn override: loaded home "${label}" (${parsed.home}, mode=${mode}${seed !== null ? `, seed=${seed}` : ''})`);
        return { coord, mode, seed, label };
    } catch (err) {
        printWarning(`AP spawn override: failed to parse ${OVERRIDES_PATH}, home is vanilla Lumbridge (${err instanceof Error ? err.message : err})`);
        return fallback();
    }
}

function ensureLoaded(): SpawnState {
    if (state === null) {
        state = load();
    }
    return state;
}

// The seeded home/respawn coordinate, packed. Never null: vanilla Lumbridge when no
// table (or an invalid one) is present. Frozen export signature - other AP modules
// (skip-tutorial) import this exact function.
export function getHomeCoord(): number {
    return ensureLoaded().coord;
}

// Human-readable place name for the seeded home, e.g. "Falador" (city mode) or
// "mapsquare 45,52" (chunk mode). Used by the ::apspawn test command / tracker.
export function getSpawnLabel(): string {
    return ensureLoaded().label;
}

// Full metadata for spoiler/tracker use beyond the frozen getHomeCoord/getSpawnLabel
// pair - not consumed by the frozen script command, safe to extend.
export function getSpawnMeta(): { coord: number; mode: 'city' | 'chunk' | 'vanilla'; seed: number | null; label: string } {
    return { ...ensureLoaded() };
}
