import fs from 'fs';
import path from 'path';

import { recordDiscovery } from '#/engine/ApTracker.js';
import { printInfo, printWarning } from '#/util/Logger.js';

// Backing store for the ap_thieving_swap script command (Archipelago thieving
// randomizer, GitHub #6). Maps a thieving loot item's obj id to the obj id actually
// handed to the player - "pick a man's pocket, get an uncut ruby". Generated by
// tools/thieving/RandomizeThieving.ts.
//
// Identical architecture to ApGatherOverrides.ts / ApProcessOverrides.ts (read
// ApGatherOverrides' header for the fuller writeup): the table lives outside the
// compiled script pack on purpose, so reseeding only requires swapping this file and
// restarting the server - no content rebuild. The three ap_thieving_swap() wraps in
// content/scripts/skill_thieving/scripts/thieving.rs2 (pickpocket / stall / trapped
// chest reward cascades) are seed-independent; only this mapping changes per seed.
//
// Miss semantics are PASSTHROUGH (return the input id), same as gather/process: the
// natural miss meaning for an item transform is "unchanged", and it lets every
// chokepoint be a pure one-token wrap with no null branch. A missing or empty file
// therefore means every thieving reward is vanilla.

const OVERRIDES_PATH = 'data/config/ap-thieving.json';

let overrides: Map<number, number> | null = null;

function load(): Map<number, number> {
    const table = new Map<number, number>();

    if (!fs.existsSync(OVERRIDES_PATH)) {
        printInfo(`AP thieving overrides: no ${path.basename(OVERRIDES_PATH)}, thieving rewards are vanilla`);
        return table;
    }

    try {
        const parsed = JSON.parse(fs.readFileSync(OVERRIDES_PATH, 'utf8')) as { map?: Record<string, number> };
        for (const [product, replacement] of Object.entries(parsed.map ?? {})) {
            if (!/^\d+$/.test(product) || !Number.isInteger(replacement) || replacement < 0) {
                printWarning(`AP thieving overrides: skipping malformed entry ${product} -> ${replacement}`);
                continue;
            }
            table.set(parseInt(product, 10), replacement);
        }
        printInfo(`AP thieving overrides: loaded ${table.size} loot swap(s)`);
    } catch (err) {
        printWarning(`AP thieving overrides: failed to parse ${OVERRIDES_PATH}, thieving rewards are vanilla (${err instanceof Error ? err.message : err})`);
    }

    return table;
}

// returns the replacement obj id for a thieving loot item, or the item itself
// (vanilla passthrough) on miss.
export function getThievingSwap(product: number): number {
    if (overrides === null) {
        overrides = load();
    }

    const swapped = overrides.get(product) ?? product;
    if (swapped !== product) {
        // the lookup moment IS "the player actually stole this" - the rarity roll has
        // already passed by the time the wrap runs, so nothing is revealed for loot the
        // player never received. Record it for the browser discovery tracker
        // (docs/tracker-map.md).
        recordDiscovery('thieving', String(product), String(swapped));
    }
    return swapped;
}

// table size for the tracker's "N of M discovered" counters - not a spoiler, just a count.
export function getThievingOverrideCount(): number {
    if (overrides === null) {
        overrides = load();
    }
    return overrides.size;
}
