#!/usr/bin/env python3
"""Regenerate the notable-kill npc_type chains in ap_checks.rs2.

The first/notable-kill checks (`first_kill_skeleton`, `first_kill_dwarf`, ...)
fire from [proc,ap_track_kill], which matches the dying NPC by npc_type. That
list was hand-written and only covered the handful of variants that were
obvious from the npc names, so most palette swaps and quest duplicates of the
same monster never fired their check: killing the Edgeville-dungeon skeleton
worked, killing the Stronghold/Melzar's/Draynor-manor ones (giantskeleton,
dragonslayer_skeleton, skull_skeleton) did not, even though all four are just
"Skeleton" in game.

The fix is to stop hand-listing. A monster group is defined by the DISPLAY NAME
in the .npc config (`name=`) plus "is attackable" (some op is Attack) - i.e.
exactly what the player sees when they right-click the thing. Every npc type in
the content set with that name is in the group, so a content update that adds
another Skeleton picks it up on the next run of this script.

EXTRAS covers the one case the name rule can't: monsters the player reads as
part of the group but the config names differently (Chaos dwarf -> dwarf, which
the hand-written list already counted - dropping it would be a regression).

Run from the repo root, then rebuild the pack (content change):
    python3 scripts/gen-kill-groups.py [--server ../Server] [--check]
    cd ../Server/engine && npx tsx tools/pack/Build.ts

--check exits 1 instead of writing if the file is out of date, for CI//loop use.
"""
import argparse
import json
import os
import re
import sys

BEGIN = '// >>> GENERATED by scripts/gen-kill-groups.py - do not hand-edit below'
END = '// <<< END GENERATED'

# (bit on %ap_kills, check id, display names that form the group, extra npc types)
# Keep in sync with the ap_kills watch table in
# overlays/engine/data/config/ap-checks.json - verified below, not assumed.
GROUPS = [
    (1, 'first_kill_goblin', ['Goblin'], []),
    (2, 'first_kill_cow', ['Cow'], []),
    (3, 'first_kill_chicken', ['Chicken'], []),
    (4, 'first_kill_rat', ['Rat'], []),
    (5, 'first_kill_guard', ['Guard'], []),
    (6, 'first_kill_dwarf', ['Dwarf'], ['dwarf_chaos']),
    (7, 'first_kill_skeleton', ['Skeleton'], []),
    (8, 'first_kill_zombie', ['Zombie'], []),
    (9, 'first_kill_ghost', ['Ghost'], []),
    (10, 'first_kill_moss_giant', ['Moss giant'], []),
    (11, 'first_kill_ice_giant', ['Ice giant'], []),
    (12, 'first_kill_lesser_demon', ['Lesser demon'], []),
    (13, 'first_kill_black_knight', ['Black Knight'], []),
    (14, 'first_kill_green_dragon', ['Green dragon'], []),
]

OP_KEYS = ('op1', 'op2', 'op3', 'op4', 'op5')


def npc_order(content):
    """npc type names in pack-id order - the id order the chains are emitted in."""
    path = os.path.join(content, 'pack', 'npc.pack')
    with open(path, encoding='utf-8') as fh:
        return [line.strip().split('=', 1)[1] for line in fh if line.strip()]


def npc_configs(content):
    """{npc type name: {key: value}} across every .npc in the content set.

    The base rev's npcs live in scripts/_unpack/<rev>/all.npc; quest and area
    packs add their own. No npc is defined twice (checked), so walk order does
    not matter.
    """
    out = {}
    for dirpath, _, filenames in os.walk(os.path.join(content, 'scripts')):
        if '.ap-backup' in dirpath:
            continue
        for filename in filenames:
            if not filename.endswith('.npc'):
                continue
            path = os.path.join(dirpath, filename)
            current = None
            with open(path, encoding='utf-8', errors='replace') as fh:
                for line in fh:
                    line = line.strip()
                    header = re.match(r'^\[(.+)\]$', line)
                    if header:
                        current = header.group(1)
                        if current in out:
                            sys.exit('npc {} defined twice ({} and {})'.format(
                                current, out[current]['_file'], path))
                        out[current] = {'_file': path}
                    elif current and '=' in line and not line.startswith('//'):
                        key, value = line.split('=', 1)
                        out[current].setdefault(key, value)
    return out


def undeathed(content):
    """npc types whose [ai_queue3,...] death script never reaches ~npc_death.

    Multi-stage bosses and scripted quest deaths (Delrith, the Black Knight
    Titan, the shapeshifter) run their own death path instead of the shared
    [proc,npc_death], which is where ~ap_track_kill is hooked - a kill check on
    one of those would never fire, so the generator refuses to emit it.
    Everything else falls through to [ai_queue3,_] -> ~npc_default_death ->
    ~npc_death, so no death script at all is fine.
    """
    blocks = {}
    for dirpath, _, filenames in os.walk(os.path.join(content, 'scripts')):
        if '.ap-backup' in dirpath:
            continue
        for filename in filenames:
            if not filename.endswith('.rs2'):
                continue
            with open(os.path.join(dirpath, filename), encoding='utf-8', errors='replace') as fh:
                for block in re.split(r'(?m)^\[', fh.read()):
                    blocks[block.split(']')[0]] = block

    def reaches_death(header, seen):
        block = blocks.get(header)
        if block is None or header in seen:
            return False
        seen.add(header)
        if 'npc_death' in block:
            return True
        # Tail-jumps (@label / @script) continue the death path in another
        # block, often in another file - follow them before giving up.
        return any(reaches_death(prefix + jump, seen)
                   for jump in re.findall(r'@(\w+)', block)
                   for prefix in ('label,', 'ai_queue3,'))

    return {header.split(',', 1)[1] for header in blocks
            if header.startswith('ai_queue3,')
            and header != 'ai_queue3,_'
            and not reaches_death(header, set())}


def resolve(content):
    order = npc_order(content)
    rank = {name: i for i, name in enumerate(order)}
    configs = npc_configs(content)
    dead_ends = undeathed(content)
    resolved = []
    for bit, check, names, extras in GROUPS:
        members = [n for n in order
                   if configs.get(n, {}).get('name') in names
                   and any(configs.get(n, {}).get(k) == 'Attack' for k in OP_KEYS)]
        for extra in extras:
            if extra not in rank:
                sys.exit('{}: extra npc "{}" is not in npc.pack'.format(check, extra))
            if extra not in members:
                members.append(extra)
        members.sort(key=lambda n: rank[n])
        if not members:
            sys.exit('{}: no attackable npc named {}'.format(check, ' / '.join(names)))
        blocked = sorted(set(members) & dead_ends)
        if blocked:
            sys.exit('{}: {} die outside ~npc_death, the check could never fire'.format(
                check, ', '.join(blocked)))
        resolved.append((bit, check, names, members))
    return resolved


def verify_watches(repo, resolved):
    """The bits only do anything because ap-checks.json watches them."""
    path = os.path.join(repo, 'overlays', 'engine', 'data', 'config', 'ap-checks.json')
    with open(path, encoding='utf-8') as fh:
        watches = json.load(fh)['watches']
    have = {(w['value'], w['check']) for w in watches
            if w.get('varp') == 'ap_kills' and w.get('mode') == 'bit'}
    want = {(bit, check) for bit, check, _, _ in resolved}
    missing = sorted(want - have)
    if missing:
        sys.exit('ap-checks.json is missing ap_kills bit watches: {}'.format(missing))


def render(resolved):
    lines = [BEGIN,
             '// A group is every attackable npc type whose config name= matches, so',
             '// palette swaps and quest duplicates of the same monster all count.']
    for index, (bit, check, names, members) in enumerate(resolved):
        opener = 'if' if index == 0 else '} else if'
        conditions = ' | '.join('npc_type = {}'.format(m) for m in members)
        lines.append('{} ({}) {{'.format(opener, conditions))
        lines.append('    ~ap_kill_mark({}, "{}"); // {}'.format(bit, check, ' / '.join(names)))
    lines.append('}')
    lines.append(END)
    return lines


def main():
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--server', default=os.path.join(os.path.dirname(repo), 'Server'),
                        help='vanilla LostCityRS checkout holding content/')
    parser.add_argument('--check', action='store_true',
                        help='exit 1 if ap_checks.rs2 is out of date instead of writing it')
    args = parser.parse_args()

    content = os.path.join(args.server, 'content')
    if not os.path.isdir(content):
        sys.exit('no content dir at {} - pass --server'.format(content))

    resolved = resolve(content)
    verify_watches(repo, resolved)

    target = os.path.join(repo, 'overlays', 'content', 'scripts', 'ap', 'ap_checks.rs2')
    with open(target, encoding='utf-8', newline='') as fh:
        text = fh.read()
    newline = '\r\n' if '\r\n' in text else '\n'
    block = newline.join(render(resolved))
    pattern = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        sys.exit('{} has no "{}" ... "{}" block to replace'.format(target, BEGIN, END))
    updated = pattern.sub(lambda _: block, text, count=1)

    for _, check, names, members in resolved:
        print('{:24} {:2} npc types  {}'.format(check, len(members), ' '.join(members)))

    if updated == text:
        print('\nap_checks.rs2 already up to date')
        return
    if args.check:
        sys.exit('\nap_checks.rs2 is out of date - run scripts/gen-kill-groups.py')
    with open(target, 'w', encoding='utf-8', newline='') as fh:
        fh.write(updated)
    print('\nwrote {} - rebuild the pack (npx tsx tools/pack/Build.ts)'.format(target))


if __name__ == '__main__':
    main()
