#!/usr/bin/env python3
"""Regenerate overlays/content/scripts/ap/configs/ap_rewards.dbrow.

Rows are (min_level, obj, qty, qty_max). min_level is read against the
category's governing stat in ~ap_level_for_category; it is a BIAS anchor now,
not a hard cutoff (see ~ap_tier_weight), so a tier above your level is rare
rather than impossible.
"""
import re
import sys

HEADER = """// Archipelago check reward pool. See docs/goals-and-checks.md "Feature 2" for
// the design and docs/ap-yaml-options.md for the tuning knobs. Static data, one
// row per (category, item) option.
//
// GENERATED by scripts/gen-rewards.py - hand edits are fine but re-running the
// generator overwrites them; prefer editing the generator.
//
// min_level is the level at which the tier becomes RELEVANT, checked against the
// category's governing stat (or %qp for cash). It is no longer a hard gate:
// ~ap_tier_weight turns it into a bias, so you mostly get what you can use, still
// sometimes get a tier or two above you, and rarely get something far out of
// reach. qty/qty_max bound a uniform quantity roll.
"""

CATEGORIES = []


def cat(name, comment, rows):
    CATEGORIES.append((name, comment, rows))


# ---------------------------------------------------------------------------
# packs - multi-roll categories (rewardPackRolls, default 3 rolls each)
# ---------------------------------------------------------------------------

cat("ores", "ores (smithing - what CONSUMES the ore, so a smith who never mines\n// still gets usable material). Coal is deliberately the fattest stack in the\n// table: it is the single biggest bottleneck in a randomized world, where the\n// gathering shuffle can take coal rocks away from you entirely.", [
    (1, "clay", 15, 30),
    (1, "copper_ore", 20, 40),
    (1, "tin_ore", 20, 40),
    (15, "iron_ore", 20, 40),
    (20, "silver_ore", 10, 20),
    (30, "coal", 40, 90),
    (40, "gold_ore", 8, 16),
    (50, "mithril_ore", 12, 25),
    (70, "adamantite_ore", 8, 16),
    (85, "runite_ore", 2, 5),
])

cat("bars", "bars (smithing). Worth more than the equivalent ore in a default seed:\n// the processing shuffle means smelting may not produce the bar the recipe\n// names, so a bar in hand skips a randomized step.", [
    (1, "bronze_bar", 15, 30),
    (15, "iron_bar", 12, 25),
    (20, "silver_bar", 8, 15),
    (30, "steel_bar", 12, 25),
    (40, "gold_bar", 6, 12),
    (50, "mithril_bar", 8, 16),
    (70, "adamantite_bar", 5, 10),
    (85, "runite_bar", 2, 4),
])

cat("herbs", "herbs (herblore). Absorbs the old herb_supplies category: unidentified\n// herbs at their cleaning level, secondaries at the level of the potion that\n// wants them, and vials in bulk.", [
    (1, "vial_water", 10, 20),
    (1, "unidentified_guam", 6, 12),
    (1, "eye_of_newt", 8, 15),
    (5, "unidentified_marentill", 5, 10),
    (11, "unidentified_tarromin", 5, 10),
    (12, "limpwurt_root", 5, 10),
    (20, "unidentified_harralander", 4, 9),
    (22, "red_spiders_eggs", 5, 10),
    (25, "unidentified_ranarr", 4, 8),
    (26, "chocolate_dust", 4, 8),
    (30, "white_berries", 4, 8),
    (38, "snape_grass", 4, 8),
    (40, "unidentified_irit", 4, 8),
    (45, "jangerberries", 4, 8),
    (48, "unidentified_avantoe", 3, 7),
    (54, "unidentified_kwuarm", 3, 7),
    (60, "wine_of_zamorak", 3, 6),
    (63, "blue_dragon_scale", 3, 6),
    (65, "unidentified_cadantine", 3, 6),
    (67, "unidentified_lantadyme", 3, 6),
    (68, "unicorn_horn_dust", 3, 6),
    (69, "dragon_scale_dust", 3, 6),
    (70, "unidentified_dwarf_weed", 3, 6),
    (75, "unidentified_torstol", 2, 5),
])

cat("runes", "runes (magic). Quantities are per-pack rolls, so three air-rune rolls\n// really do stack into one usable pile.", [
    (1, "airrune", 200, 400),
    (1, "earthrune", 200, 400),
    (1, "firerune", 200, 400),
    (1, "waterrune", 200, 400),
    (1, "mindrune", 150, 300),
    (20, "bodyrune", 120, 250),
    (35, "chaosrune", 80, 160),
    (40, "cosmicrune", 60, 120),
    (44, "naturerune", 50, 100),
    (54, "lawrune", 40, 80),
    (65, "deathrune", 30, 70),
    (76, "bloodrune", 20, 45),
])

# ---------------------------------------------------------------------------
# single-roll categories
# ---------------------------------------------------------------------------

cat("armour", "armour (defence)", [
    (1, "bronze_platebody", 1, 1),
    (1, "bronze_platelegs", 1, 1),
    (1, "bronze_kiteshield", 1, 1),
    (1, "iron_platebody", 1, 1),
    (1, "iron_platelegs", 1, 1),
    (1, "iron_kiteshield", 1, 1),
    (10, "steel_platebody", 1, 1),
    (10, "steel_platelegs", 1, 1),
    (10, "steel_kiteshield", 1, 1),
    (10, "black_platebody", 1, 1),
    (10, "black_platelegs", 1, 1),
    (10, "black_kiteshield", 1, 1),
    (20, "mithril_platebody", 1, 1),
    (20, "mithril_platelegs", 1, 1),
    (20, "mithril_kiteshield", 1, 1),
    (30, "adamant_platebody", 1, 1),
    (30, "adamant_platelegs", 1, 1),
    (30, "adamant_kiteshield", 1, 1),
    (40, "rune_platebody", 1, 1),
    (40, "rune_platelegs", 1, 1),
    (40, "rune_kiteshield", 1, 1),
    (40, "dragonhide_body", 1, 1),
    (45, "viking_helmet_crush", 1, 1),
    (45, "viking_helmet_magic", 1, 1),
    (45, "viking_helmet_range", 1, 1),
    (45, "viking_helmet_slash", 1, 1),
    (60, "dragon_sq_shield", 1, 1),
])

cat("weapons", "weapons (attack)", [
    (1, "bronze_sword", 1, 1),
    (1, "bronze_scimitar", 1, 1),
    (1, "iron_sword", 1, 1),
    (1, "iron_scimitar", 1, 1),
    (10, "steel_longsword", 1, 1),
    (10, "steel_scimitar", 1, 1),
    (10, "black_longsword", 1, 1),
    (10, "black_scimitar", 1, 1),
    (20, "mithril_longsword", 1, 1),
    (20, "mithril_scimitar", 1, 1),
    (30, "adamant_longsword", 1, 1),
    (30, "adamant_scimitar", 1, 1),
    (40, "rune_longsword", 1, 1),
    (40, "rune_scimitar", 1, 1),
    (60, "dragon_dagger", 1, 1),
    (60, "dragon_mace", 1, 1),
    (60, "dragon_longsword", 1, 1),
    (60, "dragon_battleaxe", 1, 1),
    (60, "dragon_halberd", 1, 1),
])

cat("ranged_gear", "ranged_gear (ranged)", [
    (1, "shortbow", 1, 1),
    (1, "longbow", 1, 1),
    (1, "crossbow", 1, 1),
    (5, "oak_shortbow", 1, 1),
    (5, "oak_longbow", 1, 1),
    (20, "willow_shortbow", 1, 1),
    (20, "willow_longbow", 1, 1),
    (30, "maple_shortbow", 1, 1),
    (30, "maple_longbow", 1, 1),
    (40, "yew_shortbow", 1, 1),
    (40, "yew_longbow", 1, 1),
    (50, "magic_shortbow", 1, 1),
    (50, "magic_longbow", 1, 1),
])

cat("arrows", "arrows (ranged)", [
    (1, "bronze_arrow", 120, 260),
    (1, "iron_arrow", 120, 260),
    (5, "steel_arrow", 100, 220),
    (20, "mithril_arrow", 90, 180),
    (30, "adamant_arrow", 70, 150),
    (40, "rune_arrow", 50, 110),
])

cat("potions", "potions (hitpoints)", [
    (1, "4dose1attack", 1, 3),
    (1, "4dose1defense", 1, 3),
    (1, "3dose1strength", 1, 3),
    (1, "4dose1energy", 1, 3),
    (20, "4dose2energy", 1, 3),
    (20, "4dose2restore", 1, 3),
    (20, "4doseprayerrestore", 1, 3),
    (40, "4dose2attack", 1, 2),
    (40, "4dose2defense", 1, 2),
    (40, "4dose2strength", 1, 2),
    (60, "4dose2antipoison", 1, 2),
])

cat("food", "food (hitpoints)", [
    (1, "bread", 6, 14),
    (1, "cooked_meat", 6, 14),
    (1, "cooked_chicken", 6, 14),
    (20, "trout", 6, 14),
    (20, "salmon", 5, 12),
    (40, "tuna", 5, 12),
    (40, "lobster", 5, 12),
    (60, "swordfish", 4, 10),
    (80, "shark", 3, 8),
])

cat("tools", "tools (min of woodcutting and mining - see ~ap_level_for_category)", [
    (1, "bronze_axe", 1, 1),
    (1, "bronze_pickaxe", 1, 1),
    (1, "iron_axe", 1, 1),
    (1, "iron_pickaxe", 1, 1),
    (10, "steel_axe", 1, 1),
    (10, "steel_pickaxe", 1, 1),
    (10, "black_axe", 1, 1),
    (20, "mithril_axe", 1, 1),
    (20, "mithril_pickaxe", 1, 1),
    (30, "adamant_axe", 1, 1),
    (30, "adamant_pickaxe", 1, 1),
    (40, "rune_axe", 1, 1),
    (40, "rune_pickaxe", 1, 1),
])

cat("cash", "cash (quest points)", [
    (0, "coins", 500, 1200),
    (10, "coins", 2000, 4000),
    (25, "coins", 5000, 10000),
    (50, "coins", 15000, 30000),
    (100, "coins", 50000, 90000),
])

cat("runecraft_supplies", "runecraft_supplies (runecraft)", [
    (1, "blankrune", 25, 60),
    (1, "air_talisman", 1, 1),
    (2, "mind_talisman", 1, 1),
    (5, "water_talisman", 1, 1),
    (9, "earth_talisman", 1, 1),
    (14, "fire_talisman", 1, 1),
    (20, "body_talisman", 1, 1),
    (27, "cosmic_talisman", 1, 1),
    (35, "chaos_talisman", 1, 1),
    (44, "nature_talisman", 1, 1),
    (54, "law_talisman", 1, 1),
    (65, "death_talisman", 1, 1),
])

cat("crafting_supplies", "crafting_supplies (crafting)", [
    (1, "needle", 1, 1),
    (1, "thread", 5, 12),
    (1, "leather", 6, 14),
    (1, "flax", 8, 18),
    (1, "silver_bar", 5, 10),
    (5, "gold_bar", 3, 8),
    (5, "ring_mould", 1, 1),
    (6, "necklace_mould", 1, 1),
    (8, "amulet_mould", 1, 1),
    (10, "bow_string", 6, 14),
    (20, "uncut_sapphire", 3, 7),
    (27, "uncut_emerald", 2, 6),
    (34, "uncut_ruby", 2, 5),
    (43, "uncut_diamond", 1, 3),
])

cat("caskets", "caskets (hitpoints as an overall-progress proxy)", [
    (1, "ap_casket_easy", 1, 1),
    (30, "ap_casket_medium", 1, 1),
    (55, "ap_casket_hard", 1, 1),
])

cat("keepsakes", "keepsakes (flat pool - every row is min_level 1, so ~ap_tier_weight\n// hands every row the same weight and the roll is uniform)", [
    (1, "3dose1antidragon", 1, 1),
    (1, "amulet_of_accuracy", 1, 1),
    (1, "amulet_of_ghostspeak", 1, 1),
    (1, "antidragonbreathshield", 1, 1),
    (1, "cape_of_legends", 1, 1),
    (1, "excalibur", 1, 1),
    (1, "gauntlets_of_chaos", 1, 1),
    (1, "gauntlets_of_cooking", 1, 1),
    (1, "gauntlets_of_goldsmithing", 1, 1),
    (1, "gnome_amulet", 1, 1),
    (1, "ice_arrow", 50, 100),
    (1, "ice_gloves", 1, 1),
    (1, "klanks_gauntlets", 1, 1),
    (1, "silverlight", 1, 1),
    (1, "steel_gauntlets", 1, 1),
])


def main(out_path):
    lines = [HEADER]
    seen = set()
    for name, comment, rows in CATEGORIES:
        lines.append(f"\n// ---- {comment} ----\n")
        for min_level, obj, qty, qty_max in rows:
            assert qty_max >= qty >= 1 or (qty >= 0 and qty_max >= qty), (name, obj)
            # row ids must be unique: cash reuses `coins` across tiers, so the
            # tier level goes in the id.
            row_id = f"ap_reward_{name}_{obj}"
            if row_id in seen:
                row_id = f"{row_id}_{min_level}"
            assert row_id not in seen, row_id
            seen.add(row_id)
            lines.append(
                f"[{row_id}]\n"
                f"table=ap_rewards\n"
                f"data=category,{name}\n"
                f"data=min_level,{min_level}\n"
                f"data=reward,{obj}\n"
                f"data=qty,{qty}\n"
                f"data=qty_max,{qty_max}\n\n"
            )
    text = "".join(lines).rstrip("\n") + "\n"
    with open(out_path, "w", newline="\n") as fh:
        fh.write(text)
    total = sum(len(r) for _, _, r in CATEGORIES)
    print(f"wrote {out_path}: {total} rows across {len(CATEGORIES)} categories")
    for name, _, rows in CATEGORIES:
        print(f"  {name:<20} {len(rows):>3}")


if __name__ == "__main__":
    main(sys.argv[1])
